/* ==========================================================================
   The paintings.
   This file is the single source of truth for the whole site — the home page
   and the gallery both build themselves from it. To add a painting:

     1. python3 scripts/resize-images.py originals/your-photo.jpg some-slug
     2. paste the entry it prints at the top of the list below
     3. fill in the title / year / medium / dimensions / alt text

   Newest first. `featured: true` puts a painting on the home page.
   `alt` describes what the painting SHOWS — it is read aloud to visitors
   using a screen reader, and it is how the work gets found in image search.
   ========================================================================== */

const PAINTINGS = [
  {
    slug: "morning-light-over-swaledale",
    title: "Morning Light over Swaledale",
    year: 2025,
    medium: "Oil on canvas",
    dimensions: "80 × 60 cm",
    series: "Yorkshire Dales",
    featured: true,
    width: 1600,
    height: 1200,
    widths: [400, 800, 1200, 1600],
    alt: "A wide dale under a warm apricot sky, the valley floor falling away in soft bands of green and ochre.",
  },
  {
    slug: "river-bend-in-june",
    title: "River Bend in June",
    year: 2025,
    medium: "Oil on linen",
    dimensions: "90 × 60 cm",
    series: "Water",
    featured: true,
    width: 1600,
    height: 1080,
    widths: [400, 800, 1200, 1600],
    alt: "A slow river turning through summer meadows, its surface breaking into pale greens and silver.",
  },
  {
    slug: "wildflower-verge",
    title: "Wildflower Verge",
    year: 2025,
    medium: "Oil on board",
    dimensions: "45 × 55 cm",
    series: "Field Studies",
    featured: true,
    width: 1600,
    height: 1956,
    widths: [400, 800, 1200, 1600],
    alt: "A roadside bank thick with grasses and scarlet poppies, rising against a pale summer sky.",
  },
  {
    slug: "estuary-in-late-october",
    title: "Estuary in Late October",
    year: 2024,
    medium: "Oil on canvas",
    dimensions: "100 × 70 cm",
    series: "Water",
    featured: true,
    width: 1600,
    height: 1067,
    widths: [400, 800, 1200, 1600],
    alt: "A grey-green estuary at low light, wet sand catching the last of an overcast autumn sky.",
  },
  {
    slug: "dusk-over-the-moss",
    title: "Dusk over the Moss",
    year: 2024,
    medium: "Oil on canvas",
    dimensions: "120 × 75 cm",
    series: "Yorkshire Dales",
    featured: true,
    width: 1600,
    height: 1000,
    widths: [400, 800, 1200, 1600],
    alt: "Peat moorland at dusk, a burnt-orange sky pressing down onto dark, level ground.",
  },
  {
    slug: "orchard-after-rain",
    title: "Orchard After Rain",
    year: 2024,
    medium: "Oil on board",
    dimensions: "50 × 65 cm",
    series: "Field Studies",
    featured: true,
    width: 1600,
    height: 2000,
    widths: [400, 800, 1200, 1600],
    alt: "Wet orchard grass under heavy cloud, the greens deepened and the light flattened after rain.",
  },
  {
    slug: "harbour-wall-st-ives",
    title: "Harbour Wall, St Ives",
    year: 2024,
    medium: "Oil on canvas",
    dimensions: "90 × 65 cm",
    series: "Coast",
    featured: false,
    width: 1600,
    height: 1133,
    widths: [400, 800, 1200, 1600],
    alt: "A harbour wall in strong Cornish light, warm stone above deep blue-green water.",
  },
  {
    slug: "low-tide-morecambe",
    title: "Low Tide, Morecambe",
    year: 2023,
    medium: "Oil on linen",
    dimensions: "110 × 70 cm",
    series: "Coast",
    featured: false,
    width: 1600,
    height: 1033,
    widths: [400, 800, 1200, 1600],
    alt: "A vast tidal flat under a pale sky, wet sand and channels running to a distant horizon.",
  },
  {
    slug: "field-margin-august",
    title: "Field Margin, August",
    year: 2023,
    medium: "Oil on canvas",
    dimensions: "95 × 65 cm",
    series: "Field Studies",
    featured: false,
    width: 1600,
    height: 1067,
    widths: [400, 800, 1200, 1600],
    alt: "Ripe barley meeting a hedgerow under a high blue sky, the crop worked in dry gold strokes.",
  },
  {
    slug: "chapel-lane",
    title: "Chapel Lane",
    year: 2023,
    medium: "Oil on board",
    dimensions: "60 × 45 cm",
    series: "",
    featured: false,
    width: 1600,
    height: 1183,
    widths: [400, 800, 1200, 1600],
    alt: "A sunken lane in late afternoon, warm stone walls holding the last of the day's light.",
  },
  {
    slug: "winter-hedgerow",
    title: "Winter Hedgerow",
    year: 2022,
    medium: "Oil on canvas",
    dimensions: "75 × 55 cm",
    series: "Field Studies",
    featured: false,
    width: 1600,
    height: 1200,
    widths: [400, 800, 1200, 1600],
    alt: "A bare hedgerow against frost-bleached fields, worked in soft greys, browns and bone white.",
  },
  {
    slug: "studio-window",
    title: "Studio Window",
    year: 2022,
    medium: "Oil on board",
    dimensions: "40 × 50 cm",
    series: "",
    featured: false,
    width: 1600,
    height: 2011,
    widths: [400, 800, 1200, 1600],
    alt: "Daylight falling through a studio window onto a warm interior wall, quiet and largely empty.",
  },
];
